#!/usr/bin/env python3
"""Unit tests for pbx/rtp_settings_guard.py.

The guard exists because two rows of the FreePBX-generated
`/etc/asterisk/rtp_additional.conf` disagree with the values the estate is
actually configured with, and both failures are silent:

  * `Sipsettings::genConfig()` `strtolower()`s `turnusername`/`turnpassword`, so
    Asterisk authenticates to coturn with a lower-cased password. coturn answers
    `credentials are incorrect (check_stun_auth)` and TURN relay is dead.
  * `stunaddr` pointed at coturn, which is RFC 5389 and silently drops the
    cookie-less RFC 3489 request Asterisk's `main/stun.c` sends, so every call
    logged "Attempt 3 to send STUN request ... timed out".

This asserts the converger's semantics, not the live PBX: a file that carries the
mangled rows is reported (exit 1) and, on `--apply`, rewritten while every other
row survives byte-for-byte.
"""
import io
import os
import sys
import tempfile
import unittest
from contextlib import redirect_stderr

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import rtp_settings_guard as guard  # noqa: E402

STUN = "stun.l.google.com:19302"
USER = "turnuser-a0af3124ac87"
PASSWORD = "UIAf6T7hac1b9iKZ3QqiCWlFd7syLNQsDpNpr4wRU"

HEAD = """;--------------------------------------------------------------------------------;
; Do NOT edit this file as it is auto-generated by FreePBX.
;--------------------------------------------------------------------------------;
[general]
rtpstart=10101
rtpend=10120
"""


def sample(stunaddr=STUN, username=USER, password=PASSWORD):
    return HEAD + (
        "rtpchecksums=yes\n"
        "strictrtp=yes\n"
        "stunaddr=%s\n"
        "turnaddr=coturn:3478\n"
        "turnusername=%s\n"
        "turnpassword=%s\n" % (stunaddr, username, password)
    )


class GuardTest(unittest.TestCase):
    def setUp(self):
        self._dir = tempfile.TemporaryDirectory()
        self.addCleanup(self._dir.cleanup)
        self.path = os.path.join(self._dir.name, "rtp_additional.conf")

    def write(self, text):
        with open(self.path, "w", encoding="utf-8") as fh:
            fh.write(text)
        return self.path

    def read(self):
        with open(self.path, "r", encoding="utf-8") as fh:
            return fh.read()

    def run_guard(self, *argv):
        err = io.StringIO()
        with redirect_stderr(err):
            rc = guard.main(["--rtp-conf", self.path, "--stun-addr", STUN,
                             "--turn-username", USER, "--turn-password", PASSWORD,
                             *argv])
        return rc, err.getvalue()

    # ── in sync ────────────────────────────────────────────────────────────
    def test_in_sync_reports_clean(self):
        self.write(sample())
        rc, _ = self.run_guard("--check")
        self.assertEqual(0, rc)

    def test_apply_on_a_clean_file_changes_nothing(self):
        before = self.write(sample())
        rc, err = self.run_guard("--apply")
        self.assertEqual(0, rc)
        self.assertNotIn("set ", err)
        self.assertEqual(sample(), self.read())

    # ── the credential case FreePBX introduces ─────────────────────────────
    def test_lower_cased_password_is_drift(self):
        self.write(sample(password=PASSWORD.lower()))
        rc, err = self.run_guard("--check")
        self.assertEqual(1, rc)
        self.assertIn("lower-cased by FreePBX", err)
        self.assertIn("turnpassword", err)

    def test_apply_restores_the_password_case_only(self):
        self.write(sample(password=PASSWORD.lower()))
        rc, _ = self.run_guard("--apply")
        self.assertEqual(0, rc)
        self.assertEqual(sample(), self.read())
        self.assertIn("turnpassword=%s" % PASSWORD, self.read())

    def test_lower_cased_username_is_drift(self):
        self.write(sample(username=USER.upper()))
        rc, err = self.run_guard("--check")
        self.assertEqual(1, rc)
        self.assertIn("turnusername", err)

    def test_a_genuinely_different_password_is_reported_as_such(self):
        self.write(sample(password="something-else-entirely"))
        rc, err = self.run_guard("--check")
        self.assertEqual(1, rc)
        self.assertIn("disagrees with the configured value", err)
        self.assertNotIn("lower-cased", err)

    # ── the STUN row ───────────────────────────────────────────────────────
    def test_coturn_as_the_stun_server_is_drift(self):
        """The regression this guard exists for: coturn cannot answer RFC 3489."""
        self.write(sample(stunaddr="coturn:3478"))
        rc, err = self.run_guard("--check")
        self.assertEqual(1, rc)
        self.assertIn("stunaddr=coturn:3478", err)

    def test_apply_rewrites_the_stun_row(self):
        self.write(sample(stunaddr="coturn:3478"))
        rc, _ = self.run_guard("--apply")
        self.assertEqual(0, rc)
        self.assertEqual(sample(), self.read())

    def test_missing_stun_row_is_inserted_under_general(self):
        text = sample()
        text = "".join(l for l in text.splitlines(True) if not l.startswith("stunaddr="))
        self.write(text)
        rc, _ = self.run_guard("--apply")
        self.assertEqual(0, rc)
        lines = self.read().splitlines()
        self.assertEqual("stunaddr=%s" % STUN, lines[lines.index("[general]") + 1])

    def test_a_trailing_comment_does_not_hide_a_match(self):
        self.write(sample().replace("stunaddr=%s\n" % STUN,
                                    "stunaddr=%s ; discovery only\n" % STUN))
        rc, _ = self.run_guard("--check")
        self.assertEqual(0, rc)

    def test_a_row_outside_general_is_not_ours(self):
        self.write(sample() + "\n[elsewhere]\nstunaddr=coturn:3478\n")
        rc, _ = self.run_guard("--check")
        self.assertEqual(0, rc)

    def test_a_duplicated_row_is_reported(self):
        self.write(sample() + "turnpassword=%s\n" % PASSWORD.lower())
        rc, err = self.run_guard("--check")
        self.assertEqual(1, rc)
        self.assertIn("declared 2 times", err)

    # ── nothing to judge / nowhere to write ────────────────────────────────
    def test_no_expectation_is_indeterminate(self):
        self.write(sample())
        err = io.StringIO()
        with redirect_stderr(err):
            rc = guard.main(["--rtp-conf", self.path, "--stun-addr", "",
                             "--turn-username", "", "--turn-password", "", "--check"])
        self.assertEqual(2, rc)

    def test_missing_file_is_indeterminate(self):
        rc, _ = self.run_guard("--check")
        self.assertEqual(2, rc)

    # ── the entrypoint's env is the default source of truth ────────────────
    def test_env_defaults_are_used(self):
        self.write(sample(stunaddr="coturn:3478"))
        saved = dict(os.environ)
        self.addCleanup(lambda: (os.environ.clear(), os.environ.update(saved)))
        os.environ.pop("PJSIP_STUN_ADDR", None)
        os.environ["TURN_USERNAME"] = USER
        os.environ["TURN_CREDENTIAL"] = PASSWORD
        err = io.StringIO()
        with redirect_stderr(err):
            rc = guard.main(["--rtp-conf", self.path, "--apply"])
        self.assertEqual(0, rc)
        # PJSIP_STUN_ADDR unset -> the built-in legacy-compatible default.
        self.assertIn("stunaddr=%s" % guard.DEFAULT_STUN_ADDR, self.read())

    def test_pjsip_stun_addr_overrides_the_default(self):
        self.write(sample(stunaddr="coturn:3478"))
        saved = dict(os.environ)
        self.addCleanup(lambda: (os.environ.clear(), os.environ.update(saved)))
        os.environ["PJSIP_STUN_ADDR"] = "stun.example.internal:3478"
        err = io.StringIO()
        with redirect_stderr(err):
            rc = guard.main(["--rtp-conf", self.path, "--apply"])
        self.assertEqual(0, rc)
        self.assertIn("stunaddr=stun.example.internal:3478", self.read())


if __name__ == "__main__":
    unittest.main()
