#!/usr/bin/env python3
"""The PJSIP ownership check's parsing and its verdict table.

`pbx/pjsip_owner_check.py` exists to answer one question — who owns the endpoint
for an extension. Since the endpoint decision (2026-09-25) that answer is
FreePBX, extended by the portal's `[<ext>](+)` append in
`pjsip.endpoint_custom_post.conf`; a box provisioned before the decision instead
carries a `pjsip_ext_<ext>.conf` defining a second `[<ext>](webrtc-template)`,
which is the shape these tests still pin — it is what a migration has to find and
remove.

That makes three claims worth pinning here, none of which a human reads off a
config directory reliably:

  * a file is judged generated by its **header or its name**, and an
    operator-owned `_custom` file is never generated — the two signals the
    convention rests on;
  * the load tree is the `#include` closure from `pjsip.conf`, so "on disk" and
    "loaded" are different answers;
  * a duplicate is the same **(id, type)** in two files, and `[101]` appearing in
    `pjsip.endpoint.conf`, `pjsip.auth.conf` and `pjsip.aor.conf` is the benign
    case — which is why template inheritance is resolved rather than
    string-matched.

The decisive case is `test_moving_the_include_does_not_fix_the_duplicate`: it is
the measurement's whole point. The portal's include lands in a file FreePBX
rewrites, and moving it to `pjsip_custom_post.conf` makes it *survive* — into a
load tree that already defines the same endpoint, which is the state that takes
res_pjsip down with it. The tool has to be able to say both things at once,
because either one alone reads as a fix.

Run:  python3 -m unittest discover -s pbx/tests -v
"""
import contextlib
import io
import json
import os
import sys
import tempfile
import unittest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import pjsip_owner_check as check  # noqa: E402

FREEPBX_HEADER = (
    ";--------------------------------------------------------------------------------;\n"
    ";	Do NOT edit this file as it is auto-generated by FreePBX. All modifications to ;\n"
    ";	this file must be done via the web gui.                                      ;\n"
    ";--------------------------------------------------------------------------------;\n"
)

# ── the live shape ──────────────────────────────────────────────────────────
# FreePBX's generated pjsip.conf: the file the portal appends its include to.
PJSIP_CONF = FREEPBX_HEADER + """
#include pjsip.transports.conf
#include pjsip.endpoint.conf
#include pjsip.aor.conf
#include pjsip.auth.conf
#include pjsip_custom.conf
#include pjsip_custom_post.conf
"""

# The endpoint FreePBX generates for an extension with `sip` rows.
PJSIP_ENDPOINT_CONF = FREEPBX_HEADER + """
[101]
type=endpoint
context=from-internal
disallow=all
allow=ulaw
auth=101
aors=101
"""
PJSIP_AUTH_CONF = FREEPBX_HEADER + """
[101]
type=auth
auth_type=userpass
password=generated-by-freepbx
username=101
"""
PJSIP_AOR_CONF = FREEPBX_HEADER + """
[101]
type=aor
max_contacts=1
"""

# The entrypoint's WSS transport + the template every softphone endpoint
# inherits from. Operator-authored, no FreePBX header.
PJSIP_WSS_CONF = """
[transport-wss]
type=transport
protocol=wss
bind=0.0.0.0:8089

[webrtc-template](!)
type=endpoint
transport=transport-wss
context=from-internal
disallow=all
allow=ulaw,opus
webrtc=yes
"""

# What the portal writes: a second endpoint for the same id, inheriting
# `type=endpoint` from the template above.
PJSIP_EXT_101_CONF = """
[101](webrtc-template)
auth=101-auth
aors=101-aor

[101-auth]
type=auth
auth_type=userpass
password=portal-issued
username=101

[101-aor]
type=aor
max_contacts=5
"""

# Operator-owned: the file the SMS trunk's include already lives in, and the
# file a surviving include would have to move to.
PJSIP_CUSTOM_POST_CONF = """
#include pjsip_voipms_custom.conf
#include pjsip_wss.conf
"""


def live_shape(include_in: str | None = "pjsip.conf") -> dict[str, str]:
    """The box as the portal leaves it, with the include carried by `include_in`.

    `include_in=None` is the state after an Apply Config has regenerated
    `pjsip.conf` and dropped the include: the fragment is still on disk.
    """
    files = {
        "pjsip.conf": PJSIP_CONF,
        "pjsip.endpoint.conf": PJSIP_ENDPOINT_CONF,
        "pjsip.auth.conf": PJSIP_AUTH_CONF,
        "pjsip.aor.conf": PJSIP_AOR_CONF,
        "pjsip_wss.conf": PJSIP_WSS_CONF,
        "pjsip_ext_101.conf": PJSIP_EXT_101_CONF,
        "pjsip_custom_post.conf": PJSIP_CUSTOM_POST_CONF,
    }
    if include_in:
        files[include_in] = files[include_in].rstrip("\n") + "\n#include pjsip_ext_101.conf\n"
    return files


def one_owner_shape() -> dict[str, str]:
    """The state a correct fix produces: FreePBX owns nothing for 101.

    `pjsip.endpoint.conf` carries 102 (some other extension), so the file is
    still there and still generated, and 101 exists only in the portal's
    fragment — which a `_custom` file now includes.
    """
    return {
        "pjsip.conf": PJSIP_CONF,
        "pjsip.endpoint.conf": PJSIP_ENDPOINT_CONF.replace("[101]", "[102]"),
        "pjsip.auth.conf": PJSIP_AUTH_CONF.replace("[101]", "[102]"),
        "pjsip.aor.conf": PJSIP_AOR_CONF.replace("[101]", "[102]"),
        "pjsip_wss.conf": PJSIP_WSS_CONF,
        "pjsip_ext_101.conf": PJSIP_EXT_101_CONF,
        "pjsip_custom_post.conf": PJSIP_CUSTOM_POST_CONF + "#include pjsip_ext_101.conf\n",
    }


def append_shape() -> dict[str, str]:
    """The decided shape: FreePBX owns [101] and the portal extends it.

    `pjsip.endpoint_custom_post.conf` is operator-owned, FreePBX includes it and
    never regenerates it, and the portal appends `[101](+)` there — no second
    object, and no `#include` of the portal's own to be dropped.
    """
    return {
        "pjsip.conf": PJSIP_CONF.rstrip("\n") + "\n#include pjsip.endpoint_custom_post.conf\n",
        "pjsip.endpoint.conf": PJSIP_ENDPOINT_CONF,
        "pjsip.auth.conf": PJSIP_AUTH_CONF,
        "pjsip.aor.conf": PJSIP_AOR_CONF,
        "pjsip_wss.conf": PJSIP_WSS_CONF,
        "pjsip.endpoint_custom_post.conf": (
            "; appended by the Zeus portal\n[101](+)\nmedia_encryption=dtls\n"
        ),
    }


class ConfigParsingTest(unittest.TestCase):
    def test_generated_is_the_header_or_the_name(self):
        for name, text in (
            ("pjsip.conf", PJSIP_CONF),  # header
            ("pjsip.endpoint.conf", "[101]\ntype=endpoint\n"),  # name, no header
            ("extensions_additional.conf", "whatever\n"),  # name only
        ):
            self.assertTrue(check.is_generated(name, text), name)

    def test_operator_owned_files_are_never_generated(self):
        for name, text in (
            ("pjsip_custom_post.conf", PJSIP_CUSTOM_POST_CONF),
            ("pjsip.endpoint_custom_post.conf", "[101]\nwebrtc=yes\n"),
            ("pjsip_wss.conf", PJSIP_WSS_CONF),
            ("pjsip_ext_101.conf", PJSIP_EXT_101_CONF),
        ):
            self.assertFalse(check.is_generated(name, text), name)

    def test_ownership_labels_three_ways(self):
        self.assertEqual(check.ownership("pjsip.conf", PJSIP_CONF), "generated")
        self.assertEqual(
            check.ownership("pjsip_custom_post.conf", PJSIP_CUSTOM_POST_CONF), "custom"
        )
        self.assertEqual(
            check.ownership("pjsip.endpoint_custom_post.conf", ""), "custom"
        )
        self.assertEqual(check.ownership("pjsip_wss.conf", PJSIP_WSS_CONF), "other")

    def test_a_generated_header_outranks_a_custom_looking_name(self):
        """A file FreePBX wrote is generated however it is named.

        The `_custom` convention is a claim about who writes the file, and the
        header is evidence about who did. Evidence wins: a `*_custom.conf` that
        FreePBX generated is exactly the file whose edits get eaten.
        """
        text = FREEPBX_HEADER + "#include pjsip_ext_101.conf\n"
        self.assertEqual(check.ownership("pjsip_custom_post.conf", text), "generated")

    def test_sections_carry_id_base_template_and_type(self):
        cfg = check.parse_config("pjsip_ext_101.conf", PJSIP_EXT_101_CONF)
        by_id = {section.id: section for section in cfg.sections}
        self.assertIsNone(by_id["101"].type)
        self.assertEqual(by_id["101"].base, "webrtc-template")
        self.assertFalse(by_id["101"].template)
        self.assertEqual(by_id["101-auth"].type, "auth")

    def test_a_template_is_not_an_object(self):
        cfg = check.parse_config("pjsip_wss.conf", PJSIP_WSS_CONF)
        by_id = {section.id: section for section in cfg.sections}
        self.assertTrue(by_id["webrtc-template"].template)
        self.assertEqual(by_id["webrtc-template"].type, "endpoint")
        self.assertEqual(by_id["transport-wss"].type, "transport")

    def test_the_first_type_in_a_section_wins(self):
        """A second `type=` is malformed input, not a second object.

        Taking the last would let a duplicate hide: a section that declared
        `type=endpoint` and then `type=aor` would file itself under a type
        nothing else uses.
        """
        cfg = check.parse_config("x.conf", "[101]\ntype=endpoint\ntype=aor\n")
        self.assertEqual(cfg.sections[0].type, "endpoint")

    def test_include_forms_all_reduce_to_a_basename(self):
        text = (
            "#include pjsip.endpoint.conf\n"
            '#include "pjsip_ext_101.conf"\n'
            "#include <pjsip_wss.conf>\n"
            "#tryinclude pjsip_optional.conf\n"
            "#include /etc/asterisk/pjsip_custom.conf\n"
        )
        self.assertEqual(
            check.parse_config("x.conf", text).includes,
            (
                "pjsip.endpoint.conf",
                "pjsip_ext_101.conf",
                "pjsip_wss.conf",
                "pjsip_optional.conf",
                "pjsip_custom.conf",
            ),
        )

    def test_inherited_type_is_resolved_through_the_template(self):
        files = check.load_files(live_shape())
        templates = check.templates_of(files)
        section = next(
            s
            for s in files["pjsip_ext_101.conf"].sections
            if s.id == "101"
        )
        self.assertEqual(check.object_type(section, templates), "endpoint")

    def test_an_unknown_base_leaves_the_type_unresolved(self):
        files = check.load_files({"a.conf": "[101](nope)\n"})
        section = files["a.conf"].sections[0]
        self.assertIsNone(check.object_type(section, check.templates_of(files)))

    def test_a_template_does_not_inherit_from_itself(self):
        """A self-inheriting header must not hang the resolution."""
        files = check.load_files({"a.conf": "[loop](loop)\ntype=endpoint\n"})
        section = files["a.conf"].sections[0]
        self.assertEqual(check.object_type(section, check.templates_of(files)), "endpoint")


class LoadTreeTest(unittest.TestCase):
    def test_the_closure_follows_includes_recursively(self):
        files = check.load_files(
            {
                "pjsip.conf": "#include pjsip.endpoint.conf\n#include pjsip_custom_post.conf\n",
                "pjsip.endpoint.conf": "#include pjsip.auth.conf\n",
                "pjsip.auth.conf": "[101]\ntype=auth\n",
                "pjsip_custom_post.conf": "#include pjsip_voipms_custom.conf\n",
                "pjsip_voipms_custom.conf": "[voipms]\ntype=endpoint\n",
            }
        )
        self.assertEqual(
            check.include_closure(files),
            [
                "pjsip.conf",
                "pjsip.endpoint.conf",
                "pjsip_custom_post.conf",
                "pjsip.auth.conf",
                "pjsip_voipms_custom.conf",
            ],
        )

    def test_a_cycle_is_survivable(self):
        files = check.load_files({"pjsip.conf": "#include a.conf\n", "a.conf": "#include pjsip.conf\n"})
        self.assertEqual(check.include_closure(files), ["pjsip.conf", "a.conf"])

    def test_an_absent_entry_has_no_closure(self):
        files = check.load_files({"other.conf": "#include pjsip.conf\n"})
        self.assertEqual(check.include_closure(files), [])

    def test_a_fragment_on_disk_is_not_necessarily_loaded(self):
        raw = live_shape(include_in=None)
        files = check.load_files(raw)
        self.assertIn("pjsip_ext_101.conf", files)
        self.assertNotIn("pjsip_ext_101.conf", check.include_closure(files))

    def test_a_dangling_include_is_reported_not_dropped(self):
        files = check.load_files({"pjsip.conf": "#include pjsip_gone.conf\n"})
        self.assertEqual(check.missing_includes(files), [("pjsip.conf", "pjsip_gone.conf")])

    def test_an_include_that_moves_keeps_the_fragment_loaded(self):
        files = check.load_files(live_shape(include_in="pjsip_custom_post.conf"))
        self.assertIn("pjsip_ext_101.conf", check.include_closure(files))


class DefinitionsTest(unittest.TestCase):
    def test_one_id_three_generated_types_is_not_a_duplicate(self):
        """The same id in endpoint/auth/aor is three objects, and only one is [101].

        Line 6 throughout: the four-line FreePBX header, a blank, then `[101]`.
        """
        files = check.load_files(live_shape(include_in=None))
        loaded = check.definitions(files)
        self.assertEqual(loaded[("101", "auth")], [("pjsip.auth.conf", 6)])
        self.assertEqual(loaded[("101", "aor")], [("pjsip.aor.conf", 6)])
        self.assertEqual(
            loaded[("101", "endpoint")],
            [("pjsip.endpoint.conf", 6), ("pjsip_ext_101.conf", 2)],
        )

    def test_the_append_section_is_not_a_second_endpoint(self):
        """`[101](+)` extends FreePBX's endpoint; it defines no object.

        This is the endpoint decision's core claim. If the append counted as an
        endpoint, the check would report the shape it is supposed to bless as a
        duplicate — and the provisioner would refuse to create over an extension
        the portal itself had just provisioned.
        """
        files = check.load_files(append_shape())
        defs = check.definitions(files)
        self.assertEqual(defs[("101", "endpoint")], [("pjsip.endpoint.conf", 6)])
        self.assertEqual(check.portal_appends(files, "101"), "pjsip.endpoint_custom_post.conf")
        self.assertEqual(check.appended_extensions(files), {"101"})

    def test_the_portal_fragment_is_the_second_endpoint(self):
        """`definitions` is what is on disk; the load tree is applied later.

        Both definitions are listed even though only FreePBX's is loaded in this
        fixture — that is what lets the verdict separate "the endpoint exists"
        from "the portal's fragment is the one being loaded".
        """
        files = check.load_files(live_shape(include_in=None))
        loaded = check.definitions(files)
        self.assertEqual(
            loaded[("101", "endpoint")],
            [("pjsip.endpoint.conf", 6), ("pjsip_ext_101.conf", 2)],
        )
        # The template itself is not an object, so it is not listed as one.
        self.assertNotIn(("webrtc-template", "endpoint"), loaded)


class VerdictTest(unittest.TestCase):
    def judge(self, raw: dict[str, str], ext: str = "101"):
        files = check.load_files(raw)
        closure = check.include_closure(files)
        return check.verdict_endpoint(ext, files, closure, check.definitions(files))

    def test_the_live_state_is_a_duplicate_the_moment_it_loads(self):
        """The portal's include in FreePBX's own file, with FreePBX's endpoint present."""
        findings = self.judge(live_shape())
        self.assertEqual(len(findings), 1)
        self.assertIs(findings[0].ok, False)
        self.assertIn("defined 2 times", findings[0].detail)
        self.assertIn("pjsip.endpoint.conf:6", findings[0].detail)
        self.assertIn("pjsip_ext_101.conf:2", findings[0].detail)

    def test_moving_the_include_does_not_fix_the_duplicate(self):
        """The measurement's point: a surviving include walks into the collision.

        In `pjsip_custom_post.conf` the include survives Apply Config, so the
        fragment stays loaded — and the duplicate endpoint id stays with it. The
        fix is not "carry the include somewhere else"; it is "stop defining a
        second object", which is why the tool reports the collision and the
        carrier separately.
        """
        raw = live_shape(include_in="pjsip_custom_post.conf")
        findings = self.judge(raw)
        self.assertIs(findings[0].ok, False)
        self.assertIn("defined 2 times", findings[0].detail)

        includes = check.verdict_includes(check.include_carriers(check.load_files(raw)))
        portal = [f for f in includes if "pjsip_ext_101.conf" in f.detail]
        self.assertEqual(len(portal), 1)
        self.assertIs(portal[0].ok, True)
        self.assertIn("survives Apply Config", portal[0].detail)

    def test_the_include_in_a_generated_carrier_is_its_own_finding(self):
        raw = live_shape()
        includes = check.verdict_includes(check.include_carriers(check.load_files(raw)))
        portal = [f for f in includes if "pjsip_ext_101.conf" in f.detail]
        self.assertEqual(len(portal), 1)
        self.assertIs(portal[0].ok, False)
        self.assertIn("pjsip.conf (ownership: generated)", portal[0].detail)
        self.assertIn("Apply Config", portal[0].detail)

    def test_the_entrypoints_own_include_is_judged_too(self):
        """`pjsip_wss.conf` is the same defect one caller over.

        The fixture already carries the *correct* include for it in
        `pjsip_custom_post.conf`; adding the entrypoint's `pjsip.conf` one makes
        two carriers, and only the generated one is the finding — which is the
        same split the fix for the portal's include has to make.
        """
        raw = live_shape()
        raw["pjsip.conf"] = raw["pjsip.conf"] + "#include pjsip_wss.conf\n"
        includes = check.verdict_includes(check.include_carriers(check.load_files(raw)))
        wss = [f for f in includes if "`#include pjsip_wss.conf`" in f.detail]
        self.assertEqual(len(wss), 2)
        generated = next(f for f in wss if "pjsip.conf (ownership: generated)" in f.detail)
        custom = next(f for f in wss if "pjsip_custom_post.conf (ownership: custom)" in f.detail)
        self.assertIs(generated.ok, False)
        self.assertIs(custom.ok, True)

    def test_the_post_reload_state_reports_the_inert_secret(self):
        """An Apply Config drops the include: FreePBX answers, the portal's does not.

        Both facts have to come out, because either alone reads as healthy: the
        endpoint exists (calls and hardware phones work), and the fragment the
        portal handed a secret for is not loaded (no softphone registers).
        """
        findings = self.judge(live_shape(include_in=None))
        self.assertEqual(len(findings), 2, findings)
        self.assertIs(findings[0].ok, True)
        self.assertIn("pjsip.endpoint.conf:6", findings[0].detail)
        self.assertIs(findings[1].ok, False)
        self.assertIn("pjsip_ext_101.conf is on this PBX and nothing includes it", findings[1].detail)
        self.assertIn("every secret the portal issued for [101] is inert", findings[1].detail)
        self.assertIn("answers [101] from pjsip.endpoint.conf", findings[1].detail)

    def test_nothing_loads_the_fragment_at_all(self):
        """No include and no FreePBX endpoint: the secret authenticates nothing."""
        raw = one_owner_shape()
        raw["pjsip_custom_post.conf"] = PJSIP_CUSTOM_POST_CONF
        findings = self.judge(raw)
        self.assertEqual(len(findings), 1, findings)
        self.assertIs(findings[0].ok, False)
        self.assertIn("nothing in the pjsip.conf include tree loads it", findings[0].detail)

    def test_one_owner_is_a_pass(self):
        raw = one_owner_shape()
        findings = self.judge(raw)
        self.assertIs(findings[0].ok, True)
        self.assertIn("defined once", findings[0].detail)
        for finding in check.verdict_includes(check.include_carriers(check.load_files(raw))):
            self.assertIsNot(finding.ok, False, finding.detail)

    def test_a_fragment_that_does_not_define_the_extension_is_a_defect(self):
        raw = one_owner_shape()
        raw["pjsip_ext_101.conf"] = "[999](webrtc-template)\nauth=999-auth\n"
        findings = self.judge(raw)
        self.assertEqual(len(findings), 2, findings)
        # Nothing defines 101 at all, and the fragment that was supposed to is
        # loaded while naming a different extension.
        self.assertIsNone(findings[0].ok)
        self.assertIs(findings[1].ok, False)
        self.assertIn("loaded but defines no [101] endpoint", findings[1].detail)

    def test_the_decided_shape_is_a_pass_that_names_the_append(self):
        findings = self.judge(append_shape())
        self.assertEqual(len(findings), 2, findings)
        self.assertIs(findings[0].ok, True)
        self.assertIn("defined once", findings[0].detail)
        self.assertIs(findings[1].ok, True)
        self.assertIn("[101](+)", findings[1].detail)

    def test_an_append_with_nothing_to_extend_is_a_defect(self):
        """The append targets an object only if FreePBX generates one.

        If it does not, the softphone has no endpoint at all, and a check that
        stopped at "the portal appended something" would call that healthy.
        """
        raw = append_shape()
        del raw["pjsip.endpoint.conf"]
        findings = self.judge(raw)
        self.assertEqual(len(findings), 1, findings)
        self.assertIs(findings[0].ok, False)
        self.assertIn("nothing to extend", findings[0].detail)

    def test_an_extension_nothing_knows_about_is_not_evaluated(self):
        findings = self.judge(live_shape(), ext="999")
        self.assertEqual(len(findings), 1)
        self.assertIsNone(findings[0].ok)

    def test_include_ownership_is_neutral_when_there_is_no_product_include(self):
        files = check.load_files({"pjsip.conf": "#include pjsip.pizza.conf\n"})
        self.assertEqual(check.include_carriers(files), [])
        self.assertIsNone(check.verdict_includes([])[0].ok)


class AsteriskOutputTest(unittest.TestCase):
    def test_the_endpoint_header_row_is_not_an_endpoint(self):
        text = (
            "Objects found: 2\n"
            "\n"
            " Endpoint:  <Endpoint/CID.....................................>  <State.....>\n"
            "=================================================================\n"
            "  Endpoint:  <101/101>                                        Not in use\n"
            "  Endpoint:  <102/102>                                        Not in use\n"
        )
        self.assertEqual(check.parse_endpoints(text), {"101", "102"})

    def test_no_endpoints_is_an_empty_set(self):
        self.assertEqual(check.parse_endpoints("Objects found: 0\n"), set())

    def test_transports_parse_without_the_header(self):
        text = (
            "Transport:  <TransportId........>  <Type>  <cos>  <tos>\n"
            "=================================================================\n"
            "Transport:  transport-udp             udp      0      0\n"
            "Transport:  transport-wss             wss      0      0\n"
        )
        self.assertEqual(check.parse_transports(text), {"transport-udp", "transport-wss"})
        self.assertEqual(
            check.parse_transport_types(text),
            {"transport-udp": "udp", "transport-wss": "wss"},
        )

    def test_freepbx_generated_wss_id_is_still_recognised(self):
        """FreePBX names a live WSS listener by its bind, not `transport-wss`."""
        text = (
            "Transport:  0.0.0.0-udp               udp      3     96  0.0.0.0:5060\n"
            "Transport:  0.0.0.0-wss               wss      3     96  0.0.0.0:8089\n"
        )
        self.assertEqual(
            check.parse_transport_types(text),
            {"0.0.0.0-udp": "udp", "0.0.0.0-wss": "wss"},
        )
        findings = check.verdict_asterisk(
            {"101"},
            {"0.0.0.0-udp", "0.0.0.0-wss"},
            True,
            "101",
            transport_types=check.parse_transport_types(text),
        )
        wss = [f for f in findings if "WSS transport" in f.detail]
        self.assertEqual(len(wss), 1)
        self.assertIs(wss[0].ok, True)
        self.assertIn("0.0.0.0-wss", wss[0].detail)

    def test_module_state_is_three_valued(self):
        self.assertTrue(
            check.parse_module_state("res_pjsip.so  res_pjsip  Running  Core  Yes\n")
        )
        self.assertFalse(
            check.parse_module_state("res_pjsip.so  res_pjsip  Not Running  Core  Yes\n")
        )
        self.assertIsNone(check.parse_module_state("res_pjsip_options.so  Running\n"))

    def test_a_missing_wss_transport_is_a_finding(self):
        findings = check.verdict_asterisk({"101"}, {"transport-udp"}, True, "101")
        wss = [f for f in findings if "transport-wss" in f.detail]
        self.assertEqual(len(wss), 1)
        self.assertIs(wss[0].ok, False)
        self.assertIn("fails at registration", wss[0].detail)

    def test_the_wss_transport_holding_is_not_a_finding(self):
        findings = check.verdict_asterisk({"101"}, {"transport-wss"}, True, "101")
        self.assertTrue(all(f.ok is not False for f in findings), findings)

    def test_res_pjsip_not_running_names_the_duplicate(self):
        findings = check.verdict_asterisk(None, None, False, "101")
        self.assertIs(findings[0].ok, False)
        self.assertIn("duplicate object id", findings[0].detail)

    def test_endpoint_existence_is_reported_not_judged(self):
        findings = check.verdict_asterisk({"101"}, {"transport-wss"}, True, "101")
        listed = [f for f in findings if "endpoint(s) loaded" in f.detail]
        self.assertEqual(len(listed), 1)
        self.assertIsNone(listed[0].ok)
        self.assertIn("[101] is among them", listed[0].detail)


class CliTest(unittest.TestCase):
    def run_cli(self, raw: dict[str, str], *extra: str):
        with tempfile.TemporaryDirectory() as directory:
            for name, text in raw.items():
                with open(os.path.join(directory, name), "w", encoding="utf-8") as handle:
                    handle.write(text)
            out, err = io.StringIO(), io.StringIO()
            with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
                code = check.main(["pjsip_owner_check.py", "--config-dir", directory, *extra])
        return code, out.getvalue(), err.getvalue()

    def test_neither_live_nor_config_dir_is_not_a_measurement(self):
        out, err = io.StringIO(), io.StringIO()
        with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
            code = check.main(["pjsip_owner_check.py"])
        self.assertEqual(code, 2)
        self.assertIn("--live or --config-dir is required", err.getvalue())

    def test_an_empty_directory_cannot_be_evaluated(self):
        code, _out, err = self.run_cli({})
        self.assertEqual(code, 2)
        self.assertIn("no configuration was read", err)

    def test_the_live_shape_fails_with_the_duplicate_named(self):
        code, out, err = self.run_cli(live_shape())
        self.assertEqual(code, 1)
        self.assertIn("defined 2 times", out)
        self.assertIn("FAIL", err)

    def test_the_one_owner_shape_passes(self):
        code, out, _err = self.run_cli(one_owner_shape())
        self.assertEqual(code, 0)
        self.assertIn("defined once", out)

    def test_an_extension_can_be_named_instead_of_inferred(self):
        raw = one_owner_shape()
        del raw["pjsip_ext_101.conf"]
        code, out, _err = self.run_cli(raw, "--extension", "102")
        self.assertEqual(code, 0)
        self.assertIn("defined once", out)

    def test_json_carries_the_measurement_not_just_the_verdict(self):
        code, out, _err = self.run_cli(live_shape(), "--json")
        self.assertEqual(code, 1)
        payload = json.loads(out[out.index("{") :])
        self.assertEqual(payload["entry"], "pjsip.conf")
        self.assertIn("pjsip_ext_101.conf", payload["closure"])
        self.assertIn("pjsip.conf", payload["generated"])
        self.assertEqual(payload["ownership"]["pjsip_custom_post.conf"], "custom")
        self.assertEqual(payload["asterisk"]["endpoints"], None)
        self.assertEqual(payload["extensions"], ["101"])
        carriers = [row["carrier"] for row in payload["include_carriers"]]
        self.assertIn("pjsip.conf", carriers)
        self.assertIn("101/endpoint", payload["definitions"])

    def test_the_decided_shape_passes(self):
        code, out, err = self.run_cli(append_shape())
        self.assertEqual(code, 0)
        self.assertIn("defined once", out)
        self.assertNotIn("FAIL", err)

    def test_the_append_section_alone_infers_the_extension(self):
        """No fragment on the box: the default set has to come from the appends.

        Otherwise a fully migrated box — the shape the decision produces —
        reports "nothing to evaluate" and is indistinguishable from a box where
        nothing was ever provisioned.
        """
        code, out, _err = self.run_cli(append_shape(), "--json")
        self.assertEqual(code, 0)
        # A passing run prints its summary after the JSON on stdout, so the
        # payload is the object between the first `{` and the last `}`.
        payload = json.loads(out[out.index("{") : out.rindex("}") + 1])
        self.assertEqual(payload["extensions"], ["101"])

    def test_an_unreadable_config_dir_is_named(self):
        """An empty directory names itself rather than reporting a clean run."""
        code, out, err = self.run_cli({}, "--extension", "101")
        self.assertEqual(code, 2)
        self.assertIn("holds no .conf files", out)
        self.assertIn("no configuration was read", err)


class HelperTest(unittest.TestCase):
    def test_the_fragment_name_yields_the_extension(self):
        self.assertEqual(check.extension_of("pjsip_ext_101.conf"), "101")
        self.assertEqual(check.extension_of("pjsip_ext_8005.conf"), "8005")
        self.assertIsNone(check.extension_of("pjsip_custom_post.conf"))
        self.assertIsNone(check.extension_of("pjsip_wss.conf"))


if __name__ == "__main__":
    unittest.main()
