#!/usr/bin/env python3
"""Unit tests for pbx/ava_ari_check.py — the engine/PBX ARI-secret guard.

The failure this guards is silent by construction: a blank AVA_ARI_SECRET in
pbx.env is regenerated by every bootstrap run, so Asterisk accepts a password
the engine does not have, and the symptom is calls that are never answered
rather than an error naming the credential.

Run:  python3 -m unittest discover -s pbx/tests -v
"""
import os
import sys
import tempfile
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
import ava_ari_check as check  # noqa: E402


class VerdictTest(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.mkdtemp()
        self.addCleanup(lambda: __import__("shutil").rmtree(self.tmp, ignore_errors=True))
        self.engine = os.path.join(self.tmp, ".env")
        self.pbx = os.path.join(self.tmp, "pbx.env")

    def _write(self, path, text):
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text)

    def test_matching_secrets_agree(self):
        self._write(self.engine, "AVA_ARI_SECRET=deadbeef\n")
        self._write(self.pbx, "AVA_ARI_USER=zeus-ava\nAVA_ARI_SECRET=deadbeef\n")
        agreed, message = check.verdict(self.engine, self.pbx)
        self.assertTrue(agreed, message)

    def test_different_secrets_are_reported(self):
        self._write(self.engine, "AVA_ARI_SECRET=deadbeef\n")
        self._write(self.pbx, "AVA_ARI_SECRET=cafebabe\n")
        agreed, message = check.verdict(self.engine, self.pbx)
        self.assertFalse(agreed)
        self.assertIn("differs", message)
        self.assertIn(self.engine, message)
        self.assertIn(self.pbx, message)

    def test_empty_in_pbx_env_is_a_mismatch_not_a_pass(self):
        """Blank is the dangerous case: the bootstrap regenerates it per run."""
        self._write(self.engine, "AVA_ARI_SECRET=deadbeef\n")
        self._write(self.pbx, "AVA_ARI_USER=zeus-ava\nAVA_ARI_SECRET=\n")
        agreed, message = check.verdict(self.engine, self.pbx)
        self.assertFalse(agreed)
        self.assertIn("regenerates", message)

    def test_missing_pbx_env_is_a_mismatch(self):
        self._write(self.engine, "AVA_ARI_SECRET=deadbeef\n")
        agreed, message = check.verdict(self.engine, self.pbx)
        self.assertFalse(agreed)
        self.assertIn("does not exist", message)

    def test_a_host_without_an_engine_env_has_nothing_to_compare(self):
        self._write(self.pbx, "AVA_ARI_SECRET=deadbeef\n")
        agreed, message = check.verdict(self.engine, self.pbx)
        self.assertTrue(agreed)
        self.assertIn("nothing to compare", message)

    def test_an_unset_engine_secret_does_not_fail_the_pbx(self):
        self._write(self.engine, "MAGNATE_PUBLIC_URL=\n")
        self._write(self.pbx, "AVA_ARI_SECRET=cafebabe\n")
        agreed, message = check.verdict(self.engine, self.pbx)
        self.assertTrue(agreed)
        self.assertIn("no ARI credential to check", message)

    def test_comments_and_quotes_do_not_defeat_the_comparison(self):
        self._write(self.engine, 'AVA_ARI_SECRET="deadbeef"  # rotated 2026-09\n')
        self._write(self.pbx, "# AVA\nAVA_ARI_SECRET='deadbeef'\n")
        agreed, message = check.verdict(self.engine, self.pbx)
        self.assertTrue(agreed, message)


if __name__ == "__main__":
    unittest.main()
