/**
 * The portal's WebRTC endpoint fragment: what it writes, and what it says about
 * whether anything loads it.
 *
 * `src/lib/pjsip-endpoint.ts` owns a decision that used to be one wrong line:
 * the portal appended `#include pjsip_ext_<ext>.conf` to `pjsip.conf`, a file
 * FreePBX regenerates — so the include was dropped at the next Apply Config
 * while the portal kept reporting the extension as provisioned. The module now
 * writes only the fragment and reports the state, and these tests pin the three
 * things that make that safe:
 *
 *   * a framework-owned include never counts as provisioned (it is dropped, and
 *     it is a duplicate `[<ext>]` beside the endpoint FreePBX generates);
 *   * an operator-owned include does, and is named;
 *   * the fragment is the only file ever written — deleting it must not edit
 *     `pjsip.conf` either, because writing that file is the mistake.
 */
import assert from "node:assert/strict";
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { after, before, describe, it } from "node:test";

import { load, transpile } from "./ts-probe.mjs";

const FREEPBX_HEADER =
  ";\tDo NOT edit this file as it is auto-generated by FreePBX. All modifications to ;\n";

let lib;
const dirs = [];

/** A config directory built from {name: text}, removed when the file finishes. */
function confDir(files) {
  const dir = mkdtempSync(join(tmpdir(), "pjsip-conf-"));
  dirs.push(dir);
  for (const [name, text] of Object.entries(files)) writeFileSync(join(dir, name), text);
  return dir;
}

before(async () => {
  lib = await load(transpile(["src/lib/pjsip-endpoint.ts"]), "pjsip-endpoint");
});

after(() => {
  for (const dir of dirs) rmSync(dir, { recursive: true, force: true });
});

describe("the fragment", () => {
  it("is a WebRTC endpoint that uses the portal's secret, and says it is not FreePBX's", () => {
    const text = lib.renderFragment("101", "s3cret");
    assert.match(text, /\[101\]\(webrtc-template\)/);
    assert.match(text, /password = s3cret/);
    assert.match(text, /\[101-auth\]/);
    assert.match(text, /\[101-aor\]/);
    assert.match(text, /NOT FreePBX-managed/);
  });
});

describe("provisioning", () => {
  it("writes the fragment and reports today's shape as NOT provisioned", () => {
    const dir = confDir({
      "pjsip.conf": `${FREEPBX_HEADER}#include pjsip_custom_post.conf\n`,
      "pjsip_custom_post.conf": "#include pjsip_voipms_custom.conf\n",
    });
    const state = lib.provisionFragment("101", "s3cret", dir);

    assert.ok(existsSync(join(dir, lib.fragmentName("101"))));
    assert.equal(state.provisioned, false);
    assert.equal(state.requiredInclude, "#include pjsip_ext_101.conf");
    assert.match(state.reason, /#include pjsip_ext_101\.conf/);
    assert.match(state.reason, /pjsip_custom_post\.conf/);
  });

  it("never writes an include into a file FreePBX regenerates", () => {
    const before = `${FREEPBX_HEADER}#include pjsip_custom_post.conf\n`;
    const dir = confDir({ "pjsip.conf": before });

    lib.provisionFragment("101", "s3cret", dir);

    assert.equal(readFileSync(join(dir, "pjsip.conf"), "utf8"), before);
  });

  it("counts an operator-owned include as provisioned, and names it", () => {
    const dir = confDir({
      "pjsip.conf": `${FREEPBX_HEADER}#include pjsip_custom_post.conf\n`,
      "pjsip_custom_post.conf": "#include pjsip_ext_101.conf\n",
    });
    const state = lib.provisionFragment("101", "s3cret", dir);

    assert.equal(state.provisioned, true);
    assert.deepEqual(state.includes, [{ file: "pjsip_custom_post.conf", operatorOwned: true }]);
  });

  it("does not count a framework-owned include, and says why it is worse", () => {
    const dir = confDir({ "pjsip.conf": `${FREEPBX_HEADER}#include pjsip_ext_101.conf\n` });
    const state = lib.provisionFragment("101", "s3cret", dir);

    assert.equal(state.provisioned, false);
    assert.match(state.reason, /regenerates/);
    assert.match(state.reason, /\[101\]/);
  });

  it("treats an unreadable config directory as not provisioned", () => {
    const dir = mkdtempSync(join(tmpdir(), "pjsip-missing-"));
    dirs.push(dir);
    const state = lib.readFragmentState("101", join(dir, "nope"));

    assert.equal(state.provisioned, false);
    assert.deepEqual(state.includes, []);
  });

  it("ignores a commented mention of the fragment", () => {
    const dir = confDir({ "pjsip_custom_post.conf": "# once wanted #include pjsip_ext_101.conf\n" });
    assert.equal(lib.readFragmentState("101", dir).provisioned, false);
  });
});

describe("removal", () => {
  it("deletes the fragment, reports the includes that still name it, and edits neither file", () => {
    const framework = `${FREEPBX_HEADER}#include pjsip_ext_101.conf\n`;
    const operator = "#include pjsip_ext_101.conf\n";
    const dir = confDir({ "pjsip.conf": framework, "pjsip_custom_post.conf": operator });

    lib.provisionFragment("101", "s3cret", dir);
    const dangling = lib.removeFragment("101", dir);

    assert.equal(existsSync(join(dir, lib.fragmentName("101"))), false);
    assert.deepEqual(dangling, [
      { file: "pjsip_custom_post.conf", operatorOwned: true },
      { file: "pjsip.conf", operatorOwned: false },
    ]);
    assert.equal(readFileSync(join(dir, "pjsip.conf"), "utf8"), framework);
    assert.equal(readFileSync(join(dir, "pjsip_custom_post.conf"), "utf8"), operator);
  });
});
