/**
 * The portal's WebRTC settings: what it writes, and what it leaves alone.
 *
 * `src/lib/pjsip-endpoint.ts` owns the endpoint decision
 * (`docs/voice-convergence.md` §11.5): **FreePBX owns the endpoint and
 * the portal extends it**, by appending `[<ext>](+)` — Asterisk's
 * append-to-existing-section syntax — to `pjsip.endpoint_custom_post.conf`. The
 * rejected alternative was a portal-owned second endpoint under an id FreePBX
 * will not generate, which would be one the PBX cannot route to and cannot
 * report device state for.
 *
 * Four properties make that safe, and none of them is visible to a typecheck:
 *
 *   * the section is `[<ext>](+)` and carries no credential — `type`, `auth`,
 *     `aors`, `username`, `password` are FreePBX's object, and writing them is
 *     how the portal ends up owning the endpoint again;
 *   * the write is idempotent and *additive in every other byte*: the same file
 *     carries `scripts/setup.sh`'s SMS DID blocks, and a rewrite that dropped
 *     them would silently break SMS;
 *   * removal cuts one block out and nothing else;
 *   * no framework file is ever written — the include that used to be appended
 *     to `pjsip.conf` is exactly what the decision removed the need for.
 */
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { after, before, describe, it } from "node:test";

import { REPO, load, transpile } from "./ts-probe.mjs";

const hasPython = (() => {
  try {
    execFileSync("python3", ["-c", "import sys"], { stdio: "ignore" });
    return true;
  } catch {
    return false;
  }
})();

const FREEPBX_HEADER =
  ";\tDo NOT edit this file as it is auto-generated by FreePBX. All modifications to ;\n";

/** What scripts/setup.sh writes into the same post file, for the SMS DIDs. */
const SMS_BLOCK = "; SMS-capable DIDs — Auto-generated by Zeus VOIP setup\n[13025550001](+);\n";

let lib;
const dirs = [];

/** A config directory built from {name: text}, removed when the file finishes. */
function confDir(files) {
  const dir = mkdtempSync(join(tmpdir(), "pjsip-conf-"));
  dirs.push(dir);
  for (const [name, text] of Object.entries(files)) writeFileSync(join(dir, name), text);
  return dir;
}

before(async () => {
  lib = await load(transpile(["src/lib/pjsip-endpoint.ts"]), "pjsip-endpoint");
});

after(() => {
  for (const dir of dirs) rmSync(dir, { recursive: true, force: true });
});

describe("the section", () => {
  it("appends to FreePBX's endpoint instead of defining a second one", () => {
    const text = lib.renderSection("101");
    assert.match(text, /^.*\[101\]\(\+\)$/m, "the header must be the append form");
    // No object type, no credential, no address of record: those are FreePBX's.
    assert.doesNotMatch(text, /^type\s*=/m);
    assert.doesNotMatch(text, /^password\s*=/m);
    assert.doesNotMatch(text, /^username\s*=/m);
    assert.doesNotMatch(text, /^auth\s*=/m);
    assert.doesNotMatch(text, /^aors\s*=/m);
    assert.doesNotMatch(text, /webrtc-template/, "the old fragment shape is gone");
  });

  it("carries the media settings a browser needs", () => {
    const text = lib.renderSection("101");
    for (const key of ["media_encryption=dtls", "ice_support=yes", "rtcp_mux=yes", "use_avpf=yes"]) {
      assert.match(text, new RegExp(`^${key}$`, "m"), key);
    }
  });

  it("says which object it extends, for whoever finds the file", () => {
    assert.match(lib.renderSection("101"), /APPENDS to the endpoint FreePBX generates/);
  });

  it("carries no media_address — that lives in its own file", () => {
    // The portal cuts every `[<ext>](+)` in this file when it provisions a
    // softphone, so a media line written here is deleted. It goes in
    // pjsip_media_custom.conf instead (see provisionMediaAddress).
    assert.doesNotMatch(lib.renderSection("101"), /^media_address=/m);
  });
});

describe("the advertised media address", () => {
  const ADDRESSES = ["192.168.1.30", "10.0.0.5", "172.19.0.4", "127.0.0.1", "169.254.1.1", "", "coturn", "172.32.1.5"];

  it("refuses any address a LAN phone cannot reach", () => {
    assert.equal(lib.isReachableMediaAddress("192.168.1.30"), true);
    assert.equal(lib.isReachableMediaAddress("172.19.0.4"), false);
    assert.equal(lib.isReachableMediaAddress("127.0.0.1"), false);
    assert.equal(lib.isReachableMediaAddress("169.254.1.1"), false);
    assert.equal(lib.isReachableMediaAddress(""), false);
    assert.equal(lib.isReachableMediaAddress("coturn"), false);
  });

  it("takes the value from the environment, empty when it is unusable", () => {
    assert.equal(lib.mediaAddressFromEnv({ LAN_IP: "192.168.1.30" }), "192.168.1.30");
    assert.equal(lib.mediaAddressFromEnv({ PJSIP_MEDIA_ADDRESS: "192.168.1.31", LAN_IP: "192.168.1.30" }), "192.168.1.31");
    assert.equal(lib.mediaAddressFromEnv({ LAN_IP: "172.19.0.4" }), "");
    assert.equal(lib.mediaAddressFromEnv({}), "");
  });

  it("draws the same line as pbx/media_address.py", { skip: !hasPython }, () => {
    const py = JSON.parse(
      execFileSync(
        "python3",
        [
          "-c",
          [
            "import json, sys",
            "import media_address as m",
            "print(json.dumps([not m.bad_address(a) for a in json.loads(sys.argv[1])]))",
          ].join("\n"),
          JSON.stringify(ADDRESSES),
        ],
        { cwd: join(REPO, "pbx"), encoding: "utf8" },
      ),
    );
    assert.deepEqual(ADDRESSES.map((a) => lib.isReachableMediaAddress(a)), py);
  });

  it("writes the append into its own file and the #include that loads it", () => {
    const dir = confDir({});
    lib.provisionWebrtc("101", dir);
    const state = lib.provisionMediaAddress("101", dir, "192.168.1.30");

    assert.equal(state.written, true);
    assert.equal(state.file, lib.MEDIA_FILE);
    const media = readFileSync(join(dir, lib.MEDIA_FILE), "utf8");
    assert.match(media, /^\[101\]\(\+\)$/m);
    assert.match(media, /^media_address=192\.168\.1\.30$/m);
    // The shared file keeps the portal's block and gains exactly one prelude
    // include — never a media section the portal would cut.
    const shared = readFileSync(join(dir, lib.POST_FILE), "utf8");
    assert.equal(shared.split("\n")[0], lib.MEDIA_INCLUDE);
    assert.doesNotMatch(shared, /^media_address=/m);
  });

  it("replaces its own media section instead of duplicating it, and keeps the rest", () => {
    const dir = confDir({ [lib.MEDIA_FILE]: "; header\n\n[101](+)\nmedia_address=10.0.0.1\n[202](+)\nmedia_address=10.0.0.2\n" });
    lib.provisionMediaAddress("101", dir, "192.168.1.30");
    const text = readFileSync(join(dir, lib.MEDIA_FILE), "utf8");
    assert.equal((text.match(/^\[101\]\(\+\)$/gm) || []).length, 1);
    assert.doesNotMatch(text, /media_address=10\.0\.0\.1/);
    assert.ok(text.startsWith("; header"), "the tool's header survives");
    assert.match(text, /^media_address=10\.0\.0\.2$/m, "the neighbour survives");
  });

  it("renders the section pbx/media_address.py would, byte for byte", { skip: !hasPython }, () => {
    const py = JSON.parse(
      execFileSync(
        "python3",
        [
          "-c",
          [
            "import json, sys",
            "import media_address as m",
            "print(json.dumps([m.render_media_section('101', a) for a in json.loads(sys.argv[1])]))",
          ].join("\n"),
          JSON.stringify(["192.168.1.30", "10.0.0.5"]),
        ],
        { cwd: join(REPO, "pbx"), encoding: "utf8" },
      ),
    );
    // The tool's section for one endpoint is the last two lines of its file.
    for (const [i, address] of ["192.168.1.30", "10.0.0.5"].entries()) {
      assert.equal(lib.renderMediaSection("101", address), py[i]);
    }
  });

  it("adds no media_address when no reachable one is configured", () => {
    const dir = confDir({});
    const state = lib.provisionMediaAddress("101", dir, "");
    assert.equal(state.written, false);
    assert.equal(existsSync(join(dir, lib.MEDIA_FILE)), false);
  });

  it("reads each extension's own address back, and empty when there is none", () => {
    const dir = confDir({
      [lib.MEDIA_FILE]:
        "; header\n\n[101](+)\nmedia_address=192.168.1.30\n\n[202](+)\nmedia_address=10.0.0.2\n",
    });
    assert.equal(lib.readMediaAddress("101", dir), "192.168.1.30");
    assert.equal(lib.readMediaAddress("202", dir), "10.0.0.2");
    assert.equal(lib.readMediaAddress("303", dir), "");
    assert.equal(lib.readMediaAddress("101", join(dir, "nope")), "");
  });
});

describe("provisioning", () => {
  it("creates the file when there is none, and reports it as provisioned", () => {
    const dir = confDir({});
    const state = lib.provisionWebrtc("101", dir);

    assert.ok(existsSync(join(dir, lib.POST_FILE)));
    assert.equal(state.provisioned, true);
    assert.equal(state.file, lib.POST_FILE);
    assert.equal(state.requiredSection, "[101](+)");
    assert.deepEqual(state.includes, [{ file: lib.POST_FILE, operatorOwned: true }]);
    assert.match(readFileSync(join(dir, lib.POST_FILE), "utf8"), /^\[101\]\(\+\)$/m);
  });

  it("is idempotent: a second run adds nothing", () => {
    const dir = confDir({});
    lib.provisionWebrtc("101", dir);
    const once = readFileSync(join(dir, lib.POST_FILE), "utf8");
    lib.provisionWebrtc("101", dir);
    assert.equal(readFileSync(join(dir, lib.POST_FILE), "utf8"), once);
  });

  it("keeps every other block in the shared file", () => {
    // The same file carries setup.sh's SMS DIDs. A rewrite that dropped them
    // would take SMS down, and nothing else would notice.
    const dir = confDir({ [lib.POST_FILE]: SMS_BLOCK });
    lib.provisionWebrtc("101", dir);
    const text = readFileSync(join(dir, lib.POST_FILE), "utf8");
    assert.ok(text.includes("[13025550001](+);"), "the SMS block survived");
    assert.match(text, /^\[101\]\(\+\)$/m);
  });

  it("replaces a stale section of ours rather than adding a second", () => {
    const dir = confDir({
      [lib.POST_FILE]: `[101](+)\nmedia_encryption=no\n[13025550001](+);\n`,
    });
    lib.provisionWebrtc("101", dir);
    const text = readFileSync(join(dir, lib.POST_FILE), "utf8");
    assert.equal(text.match(/^\[101\]\(\+\)$/gm).length, 1);
    assert.doesNotMatch(text, /media_encryption=no/, "the superseded settings are gone");
    assert.ok(text.includes("[13025550001](+);"), "the neighbour survived the edit");
  });

  it("never writes a file FreePBX regenerates", () => {
    const framework = `${FREEPBX_HEADER}#include pjsip.endpoint_custom_post.conf\n`;
    const dir = confDir({ "pjsip.conf": framework });
    lib.provisionWebrtc("101", dir);
    assert.equal(readFileSync(join(dir, "pjsip.conf"), "utf8"), framework);
    // And no include is written anywhere: that is the point of the decision.
    assert.doesNotMatch(readFileSync(join(dir, lib.POST_FILE), "utf8"), /#include/);
  });

  it("treats an unwritable directory as not provisioned", () => {
    const dir = mkdtempSync(join(tmpdir(), "pjsip-missing-"));
    dirs.push(dir);
    assert.equal(lib.readWebrtcState("101", join(dir, "nope")).provisioned, false);
  });
});

describe("the leftover endpoint file", () => {
  it("is reported when it is still on disk, and blocks being called ready", () => {
    // The pre-decision shape: a second object with this extension's id beside
    // the one FreePBX generates.
    const dir = confDir({ [lib.legacyFragmentName("101")]: "[101](webrtc-template)\n" });
    lib.provisionWebrtc("101", dir);
    const state = lib.readWebrtcState("101", dir);

    assert.equal(state.legacyFragment, true);
    assert.equal(state.provisioned, false, "settings present but a duplicate id is still on disk");
    assert.match(state.reason, /second \[101\]/);
  });

  it("is removed on the migration path", () => {
    const dir = confDir({ [lib.legacyFragmentName("101")]: "[101](webrtc-template)\n" });
    assert.equal(lib.removeLegacyFragment("101", dir), true);
    assert.equal(lib.removeLegacyFragment("101", dir), false, "second call is a no-op");
    assert.equal(existsSync(join(dir, lib.legacyFragmentName("101"))), false);
  });
});

describe("removal", () => {
  it("cuts our block out and leaves the rest of the file byte for byte", () => {
    const dir = confDir({ [lib.POST_FILE]: SMS_BLOCK });
    lib.provisionWebrtc("101", dir);

    const state = lib.removeWebrtc("101", dir);

    assert.equal(state.provisioned, false);
    assert.equal(readFileSync(join(dir, lib.POST_FILE), "utf8"), SMS_BLOCK);
  });

  it("is a no-op on a file that never carried us", () => {
    const dir = confDir({ [lib.POST_FILE]: SMS_BLOCK });
    lib.removeWebrtc("101", dir);
    assert.equal(readFileSync(join(dir, lib.POST_FILE), "utf8"), SMS_BLOCK);
  });
});
